<?xml version="1.0" encoding="utf-8"?><Database Name="Mirim2018_35" Class="LNoticeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=14.63.199.209,5433;Initial Catalog=Mirim2018_35;Persist Security Info=True;User ID=mirim35" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Mirim2018_35ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TNotice" Member="TNotice">
    <Type Name="TNotice">
      <Column Name="theUniqueID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="theNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="theTitle" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="theContent" Type="System.String" DbType="NVarChar(2048) NOT NULL" CanBeNull="false" />
      <Column Name="theWriter" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="theDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>